# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 600, 280))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(160, 160, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background: #03A9F4 ;\n"
"border-radius: 4px;\n"
"opacity: 1;\n"
"text-align: center;\n"
"letter-spacing: 0px;\n"
"color: #FFFFFF;\n"
"text-transform: uppercase;\n"
"font-weight: medium; \n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background: #0079C2;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 210, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background: #FFFFFF ;\n"
"border-radius: 4px;\n"
"opacity: 1;\n"
"text-align: center;\n"
"letter-spacing: 0px;\n"
"color: #0079C2;\n"
"text-transform: uppercase;\n"
"font-weight: medium; \n"
"border: 1px solid #e5e5e5;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background: #e8e8e8;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 75, 420, 30))
        self.lineEdit_2.setStyleSheet("border-radius: 4px;\n"
"border-style: solid;\n"
"border-width: 1px; \n"
"border-color: #AFAEAE;")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(150, 115, 420, 30))
        self.lineEdit.setStyleSheet("border-radius: 4px;\n"
"border-style: solid;\n"
"border-width: 1px; \n"
"border-color: #AFAEAE;")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 842, 60))
        self.frame.setStyleSheet("background: #0079C2 ;\n"
"border: 1px solid #e5e5e5;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-1, -1, 170, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f10909, stop:1 #0079C2);\n"
"letter-spacing: 0px;\n"
"text-transform: uppercase;\n"
"font-weight: medium; \n"
"border: 1px solid rgb(255, 255, 255);\n"
"color: white;\n"
"border-style: solid;\n"
"border-width: 1px; \n"
"border-color: #0079C2;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("letter-spacing: 0px;\n"
"text-transform: uppercase;\n"
"font-weight: medium; \n"
"border: 1px solid rgb(255, 255, 255);\n"
"color: white;\n"
"border-style: solid;\n"
"border-width: 1px; \n"
"border-color: #0079C2;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("letter-spacing: 0px;\n"
"font-weight: medium; \n"
"border: 1px solid rgb(255, 255, 255);\n"
"color: black;\n"
"border-style: solid;\n"
"border-width: 1px; \n"
"border-color: white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("letter-spacing: 0px;\n"
"font-weight: medium; \n"
"border: 1px solid rgb(255, 255, 255);\n"
"color: black;\n"
"border-style: solid;\n"
"border-width: 1px; \n"
"border-color: white;")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход в приложение"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))
        self.pushButton_2.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", " Логин"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " Пароль"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">KMV Development</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Вход в приложение"))
        self.label_3.setText(_translate("MainWindow", "Введите логин: "))
        self.label_4.setText(_translate("MainWindow", "Введите пароль: "))
